apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-service-account
  namespace: jenkins
---
kind: Secret
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdPakNDQkNLZ0F3SUJBZ0lDRUJNd0RRWUpLb1pJaHZjTkFRRUxCUUF3Z1k4eEN6QUpCZ05WQkFZVEFsVlQKTVJFd0R3WURWUVFJREFoV2FYSm5hVzVwWVRFVU1CSUdBMVVFQ2d3TFUyaGhhMlZ5Y3lCTVlXSXhFakFRQmdOVgpCQXNNQ1VSdlkydGxjaUJGUlRFZk1CMEdBMVVFQXd3V1JHOWphMlZ5SUVWRklFbHVkR1Z5YldWa2FXRjBaVEVpCk1DQUdDU3FHU0liM0RRRUpBUllUYzJoaGEyVnlNalF5UUdkdFlXbHNMbU52YlRBZUZ3MHhPREEyTURneU1qQXoKTlRkYUZ3MHlNekEyTURjeU1qQXpOVGRhTUlHYk1Rc3dDUVlEVlFRR0V3SlZVekVSTUE4R0ExVUVDQXdJVm1seQpaMmx1YVdFeEVEQU9CZ05WQkFjTUIwSnlhWE4wYjNjeEZEQVNCZ05WQkFvTUMxTm9ZV3RsY25NZ1RHRmlNUkl3CkVBWURWUVFMREFsRWIyTnJaWElnUlVVeEdUQVhCZ05WQkFNTUVDb3VhM1ZpWlM1a2IyTnJaWEl1WldVeElqQWcKQmdrcWhraUc5dzBCQ1FFV0UzTm9ZV3RsY2pJME1rQm5iV0ZwYkM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRExpd3JxVmZXMEQwc1FFc3RVamo1QXJxM2pjWTF4SXZNM1lsb3BGYnFNCmF1TDd1eW9qbVgwSWVCNE5IVzZ2ajg4RkFIVU9VMWhSQkE2UERESWpCY1AxM2pmeWcrWEVzaEJQZlJoVy94dVgKRzhvRU9RSW5sSjVzMDZ5VG9ic0VSZ1FWdU9uaEpROWwrbU5MRHFrNHhZOGhZVEl4cU5pLzhodlhuT1loNjFNdgprak1FcWtyTzVMVzVCUldBbzNGMFZFOVZHMGtlb0hBY2Q0eFpsUHIyVVZEMk00Tmg2dit5L1ZYNm44M0pxM3pLCkJ3dThiQWR1VlhXMXpVZUpHRTdsSnhoazJhZUUxSlZhU05aWFUwTDJad0VqTjhUWEJVUHcvOWRXOHRhckhDc1IKZEt4a1NrN3d1SGtZdFROSlJsNGNxWk9sK2RCRy85L0lZK3ZxUENJWWg1U05BZ01CQUFHamdnR1FNSUlCakRBSgpCZ05WSFJNRUFqQUFNQkVHQ1dDR1NBR0crRUlCQVFRRUF3SUdRREF6QmdsZ2hrZ0JodmhDQVEwRUpoWWtUM0JsCmJsTlRUQ0JIWlc1bGNtRjBaV1FnVTJWeWRtVnlJRU5sY25ScFptbGpZWFJsTUIwR0ExVWREZ1FXQkJTcW5jVEMKZU55SlZQNjdaMk8za0xVTHlRTVNRRENCeWdZRFZSMGpCSUhDTUlHL2dCUWd5N0R6YVlFdnBxSHJjY2pPNEgzMwp2Uk4yL0tHQm9xU0JuekNCbkRFTE1Ba0dBMVVFQmhNQ1ZWTXhFVEFQQmdOVkJBZ01DRlpwY21kcGJtbGhNUkF3CkRnWURWUVFIREFkQ2NtbHpkRzkzTVJRd0VnWURWUVFLREF0VGFHRnJaWEp6SUV4aFlqRVNNQkFHQTFVRUN3d0oKUkc5amEyVnlMa1ZGTVJvd0dBWURWUVFEREJGRWIyTnJaWElnUlVVZ1VtOXZkQ0JEUVRFaU1DQUdDU3FHU0liMwpEUUVKQVJZVGMyaGhhMlZ5TWpReVFHZHRZV2xzTG1OdmJZSUNFQUF3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HCkExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1DWUdBMVVkRVFRZk1CMkNDV1J2WTJ0bGNpNWxaWUlRS2k1cmRXSmwKTG1SdlkydGxjaTVsWlRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWpSSjJoT3VPbDZjaXdYS2dhMHFSYUtFego1Ui95VnpKSGYwaGVrTTdWWWF5eGZwMVZyV1BtRTVtY3UybjVnMnk4ZElUTGFxeWthcmRjUy81dUdaT1FROTRyCnJtMTh0WVdGNndxTENSMm9HckJZTGc1ZEIycGwvNlZqREVOdDcrUDdLckxibjQ4c09TNVdTcjBaZnFuOFJsTjcKUmZ3VmhHcjNtd2dRTTdOZUJ5S1VlNUcrK1lVNjMwRUdQT1ZrdzNpVnp1QWt2Q0VXQWttTmNCY2dRZEJObkIwawpPYVZxT3llVzFHYTFFTXEwTEI0UWU5NnkvY2R6L013RzFxZWdWT0Y0NTdBWnpPVlM3Z3hiOHY3Nm1jejU1cUlOCkNmMFM2bXFKM0N6SG00czdNNVRvYzlHNDU5TnhoUi9KTkYzdHpFYUttcjlEc3RUdWsyaUw5VjlQSFZ2M1hucWgKQzh3VytpaHUveHk0RVNUMWxPWjNyQTlwSzNhdytnZGcrd3ZHdXJmcm42QjBVNmM4c1hjSmcyVytKcTZMWkFEZQo2aHMvbjh0RVZNRHVVN0R3TVZQTkFwRHZXNnhsN1d2QjBKU0F1clZLVm9qTzBvOCtsYUFvWkpZLzZydDdYaFMyCmdiRTBHNDBsRDI3QUlZM1pzdnViZkt5MTM3eUZVa1hhQ3hzRXdQSHVob1c3Mm82T3FrWmk5bExwcTdXRDlBMkEKZE1KcjB6dGFUNm9BeEZ6STl1WGRlcU1LMk5jYURQbFovVzJTNW42NHdpWjFhWEZJT29FYnBQbnVLcXpNa3NxTgpjL0Y5ek5OS0pUd2h0TTJCdnN4ckZiVDNwTnhrRTZzZHQ0YTh5SUtRdHo4ME5HaXEzQVk4eUxNazB3aHNRL3pNCjlXRGlXMTB4a0dkT3IwYTVuT1U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeTRzSzZsWDF0QTlMRUJMTFZJNCtRSzZ0NDNHTmNTTHpOMkphS1JXNmpHcmkrN3NxCkk1bDlDSGdlRFIxdXI0L1BCUUIxRGxOWVVRUU9qd3d5SXdYRDlkNDM4b1BseExJUVQzMFlWdjhibHh2S0JEa0MKSjVTZWJOT3NrNkc3QkVZRUZianA0U1VQWmZwalN3NnBPTVdQSVdFeU1hall2L0liMTV6bUlldFRMNUl6QktwSwp6dVMxdVFVVmdLTnhkRlJQVlJ0SkhxQndISGVNV1pUNjlsRlE5ak9EWWVyL3N2MVYrcC9OeWF0OHlnY0x2R3dICmJsVjF0YzFIaVJoTzVTY1laTm1uaE5TVldraldWMU5DOW1jQkl6ZkUxd1ZEOFAvWFZ2TFdxeHdyRVhTc1pFcE8KOExoNUdMVXpTVVplSEttVHBmblFSdi9meUdQcjZqd2lHSWVValFJREFRQUJBb0lCQVFEQXBGRnBab0FNc2lpKwpCcnV3eEl2QTFsSzNvRUpaSU5ZR3hpeEZGRTZpRll2TTZ1REFIc1lLM1B5OE51NEtkVlpmQ29hL1R6eVlPUG02Cmc3VjBGa0hZazBCcVpGRno3MyttYStROGVtaFhoVEtXK29uQ2dsUEs5akF3N2ZJOTRqSjlpS3k2clVPOHBkV1MKTlVjTjkxVTNKM0hGTkdRb2p2R3hDTXQ2c09uamE0OHdDVnB5T3BZb3NVTTUvMlBGUmhZNjdwck1CTTJRb25SegpMTExJdlg3Tm5xU1NSbFZiNjRYRExoR0NCejVrdWJBU3AxelpOYkYzNFV6dTBGZ0s5dTltanovem0wMzFQbWhJCkMrTlJuR2Jkc29tSU1yQlVHYjVMRjh4MHMvdG5rajN0RjR2b1ZaU1UyMS84WUpucDhkcFNGRitkem1Uem12bTEKR084MWRCV2hBb0dCQVBjWU1nODk1YStJNDhXTThtZ0NOZXp1Y3JSdzJjT09naTgxdHpmbWFvS2tjcmRqeXBOdQo5UU44a0RMVXVsMWpNM29US3hqVDF0RTA4SWlTMlM4TGlSbDJoZXpvelNTT2Mva0JNRk5mckIydzN5STRTWTIyCnAxQkNIUlUyT09QWDNROXF5Z2gyb1VzV1ZwYXNzcGNzczB6M2FSTUZ0TTZTbUMrTW5WTzdhMUpaQW9HQkFOTGgKQmNsZUZpd1haTlNBU1pKNzFzTXNGZUlxUWw1MkdENGtXQ3JzRTNicGkvNEJ3VUFaWXVNd3ZPZXhyM3hLRWxoVwpLWS9DNnpHL1V5Y29XSStuMUpiaG51bWs0SFh1cnpyMDhIdXFRdUlOSHJpT3NhT2l0ZjNNUDdsc1JMRmlKL3BKCk1CSWNiZDlsWU1STzh5WG1EYkZrVHpkdjNXcDFISytrSWFtM1pZVlZBb0dBQmFMNHFWNVpHZnIrYnlnNjgySngKaG5rZUJyMjRTZnk3UFlaMUtvSklGYmpZb1JSV3I2eE5USW9QNUFqMFEyTWE3b0wzYmJhUFpQQlhPRlpaTy9pQQpaU05PQk14K3VZSENaWURBY0haelA2NGtPT3lkeU96TXZranp6dU1Rd3luT2NpYVdlMER4aHZ2NGQ3RnkxWDRBCmpSWHJ3TEpWb0l5NWlnUWtKcC9VMytrQ2dZQjNNelVuSnlUWFZYM3NWSHZCN25odUtGeFNWRnJodEZWdHd2T0gKaDV4VkNoelV2cjh5OFdhaFQycG9lVnJkb2EwTys5MVFZdmk1VFJHK3Y2S1h5V0YwekNJY3BkTXZOblVjbVZuYQpQVnJERm5GNEYwaTRXNEFONzBkU0U2NGNxb1E0aU9oQVJJdWl6RlpQZ09VV1ZoMEZXZE1oWGYxRmNOOS9OUUxHClFXR0VaUUtCZ0N2cTZOZ0gzZ2dRSVBvN2lxNlM3VFdXZUhxTU9OdUZLNWtla2hYNXhRZVgvUVpadGxWRzJGZnIKMUtsa2ZVQzRYcTMvNkNXYWNiQUtZN3dSOW1zM0xUYy9OSUFxYWUweGNWWnd1UlhUNXJjZC9mcUlRM0ppcldyRgpmbDQ4MzlOakc2SmJPeDk1YTFmelY3ZVlKNThtU0hmNGNsWUhyRWhxWmQxaXRDN2ttL3ZXCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
metadata:
  name: jenkins-tls
  namespace: jenkins
---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins-svc
spec:
  selector:
    app: jenkins-master
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: jenkins
  name: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      serviceAccountName: jenkins-service-account
      containers:
      - image: jenkins/jenkins:lts-alpine
        name: master
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        # resources:
        # limits:
        #   cpu: 500m
        #   memory: 1500Mi
        # requests:
        #   cpu: 500m
        #   memory: 1500Mi
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: jenkins
  name: jenkins-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jenkins.kube.docker.ee
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-svc
          servicePort: 8080
  tls:
  - hosts: 
    - jenkins.kube.docker.ee
    secretName: jenkins-secret

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/jenkins_home
    server: 172.16.1.5

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow